POST https://kukunya.onrender.com/accts/signup
Content-Type: application/json

{
    "name": "new1",
    "location": "new1",
    "type": "station",
    "customId": "new1",
    "email": "new1",
    "password": "new1"
}

###
POST https://kukunya.onrender.com/accts/signin
Content-Type: application/json

{
    "customId": "new1",
    "password": "new1"
}


###
GET https://kukunya.onrender.com/accts/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGNmYmEyMDkyMjZhOWQ5ZDYxMzVhZSIsImlhdCI6MTcyMDUzMjU4OCwiZXhwIjoxNzIzMTI0NTg4fQ.AtcH2l60Pi7zsoJHhGjm20ljgWEnahm89W6LTivxBwE

###
POST http://localhost:3000/auth/user/signup
Content-Type: application/json

{
    "first_name": "mayowa",
    "last_name": "yusuf",
    "NIN": "12345678901",
    "customId": "new1",
    "email": "mayowayusuf3004@gmail.com",
    "password": "mayowa"
}
###

POST http://localhost:3000/auth/user/signin
Content-Type: application/json

{
    "email": "mayowayusuf3004@gmail.com",
    "password": "mayowa"
}

###
GET http://localhost:3000/auth/user/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGQ0ZmY0NjY5MmI2NDhmMzA3OTBiNyIsImlhdCI6MTcyMDUzNzc4OSwiZXhwIjoxNzIzMTI5Nzg5fQ.Ow5oDGAepv69_JuyFk0XYlNto7wgPl2qtuqkSMsSUGM